name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Set DOTNET_ROOT and update PATH
      run: |
        echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Install EF Core CLI tools
      run: dotnet tool install --global dotnet-ef

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Apply migrations to database
      run: dotnet ef database update

    - name: Test
      run: dotnet test --no-build --verbosity normal
